import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import  SearchBar  from '@/composants/Search_bar';
import  InterFace from '@/composants/InterfaceMap';
import Hitmap from '@/composants/Hitmap'; 
const inter = Inter({ subsets: ['latin'] })

export default function Home({ maisons }) {
  console.log(maisons)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto">
      <h1 className="text-3xl font-bold underline text-red-500">
      Wellcome
        </h1>
            <SearchBar></SearchBar>
      <div>
          <InterFace></InterFace>
      </div>

      </main>
    </>
  )
}

export async function getStaticProps(ctx) {
  const data = import('../data/homes.json');
  return {
    props: {
      maisons: (await data).default,
    }
  }
}